/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tugasakhir1;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author user
 */
public class DashboardTA extends javax.swing.JPanel {

    /**
     * Creates new form DashboardTA
     */
    public DashboardTA() {
        initComponents();
        penjualan();
        penjualanbulanini();
        penjualantahunini();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gradient1 = new pallete.Gradient();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tahun = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        ttotalpenj = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        bulan = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        ttotalpenj1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gradient1.setBackground(new java.awt.Color(246, 172, 182));
        gradient1.setColorEnd(new java.awt.Color(255, 235, 235));
        gradient1.setColorStart(new java.awt.Color(255, 235, 235));
        gradient1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 18)); // NOI18N
        jLabel1.setText("Halo!!! Selamat datang di Toko Kami ");
        gradient1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 30, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 204, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Penjualan Bulan Lalu");

        tahun.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tahun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tahun.setText("000");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tahun, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tahun)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        gradient1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 190, 110));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/—Pngtree—pink  double layer birthday_5378649.png"))); // NOI18N
        gradient1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 370, 299, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/—Pngtree—sweet cupcake with chocolate cookie_14659421.png"))); // NOI18N
        gradient1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, -70, 440, 420));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Penjualan Minggu Ini");

        ttotalpenj.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        ttotalpenj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ttotalpenj.setText("000");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ttotalpenj, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ttotalpenj)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        gradient1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 180, 110));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Penjualan Bulan Ini");

        bulan.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        bulan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bulan.setText("000");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bulan, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bulan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gradient1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 190, 110));

        jPanel9.setBackground(new java.awt.Color(204, 153, 255));
        jPanel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText(" Penjualan Hari Ini");

        ttotalpenj1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        ttotalpenj1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ttotalpenj1.setText("000");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ttotalpenj1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ttotalpenj1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        gradient1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 170, 110));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/aTA.jpg"))); // NOI18N
        jScrollPane1.setViewportView(jLabel3);

        gradient1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 930, 360));

        add(gradient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 650));
    }// </editor-fold>//GEN-END:initComponents

    private void penjualan(){
         try {
            Connection c = KoneksiRoti.ConfigDB();
            Statement s = c.createStatement();
            String sql = "SELECT COUNT(*) AS total_penjualan_hari_ini from transaksi WHERE tanggal = CURDATE();";
            ResultSet r = s.executeQuery(sql);
            if (r.next()) {
                String Total = r.getString("total_penjualan_hari_ini");
          ttotalpenj1.setText(Total);
         }
         } catch (Exception e) {
            e.printStackTrace();
        }
    }
         private void penjualanbulanini() {
    try {
        Connection c = KoneksiRoti.ConfigDB();
        Statement s = c.createStatement();
        String sql = "SELECT SUM(totalbeli) AS total_penjualan_bulan_ini FROM transaksi WHERE MONTH(tanggal) = MONTH(CURDATE()) AND YEAR(tanggal) = YEAR(CURDATE());";
        ResultSet r = s.executeQuery(sql);
        if (r.next()) {
            String Total = r.getString("total_penjualan_bulan_ini");
            bulan.setText(Total);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}

        private void penjualantahunini() {
    try {
        Connection c = KoneksiRoti.ConfigDB();
        Statement s = c.createStatement();
        String sql = "SELECT SUM(totalbeli) AS total_penjualan_tahun_ini FROM transaksi WHERE YEAR(tanggal) = YEAR(CURDATE());";
        ResultSet r = s.executeQuery(sql);
        if (r.next()) {
            String Total = r.getString("total_penjualan_tahun_ini");
            tahun.setText(Total);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bulan;
    private pallete.Gradient gradient1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tahun;
    private javax.swing.JLabel ttotalpenj;
    private javax.swing.JLabel ttotalpenj1;
    // End of variables declaration//GEN-END:variables
}
