/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasakhir1;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import javax.swing.UIManager;
/**
 *
 * @author user
 */
public class Mainframe extends javax.swing.JFrame {

    /**
     * Creates new form Mainframe
     */
    
    private String userID;
            
    public Mainframe(String userID) {
        initComponents();
        this.userID = userID;
        Content.removeAll();
        Content.add(new DashboardTA());
        Content.repaint();
        Content.revalidate();
    }
    
    public String getUserID(){
        return userID;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BarAtas = new pallete.Gradient();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SideBar = new javax.swing.JPanel();
        MenuDashboard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MenuKue = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        History = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        MenuPenjualan = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        MenuAbout = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        MenuLogOut = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        MenuUser = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        BarAtas.setColorEnd(new java.awt.Color(246, 172, 182));
        BarAtas.setColorStart(new java.awt.Color(246, 172, 182));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/snapedit_1718720491617.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 24)); // NOI18N
        jLabel4.setText("TOKO ROTI ");

        jLabel5.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 24)); // NOI18N
        jLabel5.setText("LELY'S KITCHEN");

        javax.swing.GroupLayout BarAtasLayout = new javax.swing.GroupLayout(BarAtas);
        BarAtas.setLayout(BarAtasLayout);
        BarAtasLayout.setHorizontalGroup(
            BarAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarAtasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(BarAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        BarAtasLayout.setVerticalGroup(
            BarAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
            .addGroup(BarAtasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SideBar.setBackground(new java.awt.Color(238, 202, 207));

        MenuDashboard.setBackground(new java.awt.Color(238, 202, 207));
        MenuDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuDashboardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuDashboardMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel1.setText("Dashboard");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/menu (2).png"))); // NOI18N

        javax.swing.GroupLayout MenuDashboardLayout = new javax.swing.GroupLayout(MenuDashboard);
        MenuDashboard.setLayout(MenuDashboardLayout);
        MenuDashboardLayout.setHorizontalGroup(
            MenuDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuDashboardLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MenuDashboardLayout.setVerticalGroup(
            MenuDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        MenuKue.setBackground(new java.awt.Color(238, 202, 207));
        MenuKue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuKueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuKueMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuKueMousePressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel18.setText("Menu Kue");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/oven.png"))); // NOI18N

        javax.swing.GroupLayout MenuKueLayout = new javax.swing.GroupLayout(MenuKue);
        MenuKue.setLayout(MenuKueLayout);
        MenuKueLayout.setHorizontalGroup(
            MenuKueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuKueLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MenuKueLayout.setVerticalGroup(
            MenuKueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        History.setBackground(new java.awt.Color(238, 202, 207));
        History.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HistoryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HistoryMousePressed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel20.setText("History");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/breads.png"))); // NOI18N

        javax.swing.GroupLayout HistoryLayout = new javax.swing.GroupLayout(History);
        History.setLayout(HistoryLayout);
        HistoryLayout.setHorizontalGroup(
            HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HistoryLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HistoryLayout.setVerticalGroup(
            HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        MenuPenjualan.setBackground(new java.awt.Color(238, 202, 207));
        MenuPenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuPenjualanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuPenjualanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuPenjualanMousePressed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel22.setText("Penjualan");

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/save-money.png"))); // NOI18N

        javax.swing.GroupLayout MenuPenjualanLayout = new javax.swing.GroupLayout(MenuPenjualan);
        MenuPenjualan.setLayout(MenuPenjualanLayout);
        MenuPenjualanLayout.setHorizontalGroup(
            MenuPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPenjualanLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MenuPenjualanLayout.setVerticalGroup(
            MenuPenjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        MenuAbout.setBackground(new java.awt.Color(238, 202, 207));
        MenuAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuAboutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuAboutMousePressed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel26.setText("About");

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/about.png"))); // NOI18N

        javax.swing.GroupLayout MenuAboutLayout = new javax.swing.GroupLayout(MenuAbout);
        MenuAbout.setLayout(MenuAboutLayout);
        MenuAboutLayout.setHorizontalGroup(
            MenuAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuAboutLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MenuAboutLayout.setVerticalGroup(
            MenuAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        MenuLogOut.setBackground(new java.awt.Color(238, 202, 207));
        MenuLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuLogOutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuLogOutMousePressed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel28.setText("Log Out");

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/logout (1).png"))); // NOI18N

        javax.swing.GroupLayout MenuLogOutLayout = new javax.swing.GroupLayout(MenuLogOut);
        MenuLogOut.setLayout(MenuLogOutLayout);
        MenuLogOutLayout.setHorizontalGroup(
            MenuLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLogOutLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MenuLogOutLayout.setVerticalGroup(
            MenuLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        MenuUser.setBackground(new java.awt.Color(238, 202, 207));
        MenuUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuUserMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuUserMousePressed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/profile-user.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel8.setText("User");

        javax.swing.GroupLayout MenuUserLayout = new javax.swing.GroupLayout(MenuUser);
        MenuUser.setLayout(MenuUserLayout);
        MenuUserLayout.setHorizontalGroup(
            MenuUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuUserLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        MenuUserLayout.setVerticalGroup(
            MenuUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout SideBarLayout = new javax.swing.GroupLayout(SideBar);
        SideBar.setLayout(SideBarLayout);
        SideBarLayout.setHorizontalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MenuKue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MenuLogOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(History, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MenuAbout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MenuPenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MenuUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SideBarLayout.setVerticalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(MenuDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MenuUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MenuKue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(History, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MenuPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MenuAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MenuLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        Content.setBackground(new java.awt.Color(255, 255, 255));
        Content.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(BarAtas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(SideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, 1236, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BarAtas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuDashboardMouseEntered
        // TODO add your handling code here:
        MenuDashboard.setBackground(new Color(246,172,182));
    }//GEN-LAST:event_MenuDashboardMouseEntered

    private void MenuKueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuKueMouseEntered
        // TODO add your handling code here:
        MenuKue.setBackground(new Color(246,172,182));
    }//GEN-LAST:event_MenuKueMouseEntered

    private void HistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoryMouseEntered
        // TODO add your handling code here:
        History.setBackground(new Color(246,172,182));
    }//GEN-LAST:event_HistoryMouseEntered

    private void MenuPenjualanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPenjualanMouseEntered
        // TODO add your handling code here:
        MenuPenjualan.setBackground(new Color(246,172,182));
    }//GEN-LAST:event_MenuPenjualanMouseEntered

    private void MenuAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuAboutMouseEntered
        // TODO add your handling code here:
        MenuAbout.setBackground(new Color(246,172,182));
    }//GEN-LAST:event_MenuAboutMouseEntered

    private void MenuLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLogOutMouseEntered
        // TODO add your handling code here:
        MenuLogOut.setBackground(new Color(246,172,182));
    }//GEN-LAST:event_MenuLogOutMouseEntered

    private void MenuDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuDashboardMouseExited
        // TODO add your handling code here:
        MenuDashboard.setBackground(new Color(238,202,207));
    }//GEN-LAST:event_MenuDashboardMouseExited

    private void MenuKueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuKueMouseExited
        // TODO add your handling code here:
        MenuKue.setBackground(new Color(238,202,207));
    }//GEN-LAST:event_MenuKueMouseExited

    private void HistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoryMouseExited
        // TODO add your handling code here:
        History.setBackground(new Color(238,202,207));
    }//GEN-LAST:event_HistoryMouseExited

    private void MenuPenjualanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPenjualanMouseExited
        // TODO add your handling code here:
       MenuPenjualan.setBackground(new Color(238,202,207));
    }//GEN-LAST:event_MenuPenjualanMouseExited

    private void MenuAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuAboutMouseExited
        // TODO add your handling code here:
        MenuAbout.setBackground(new Color(238,202,207));
    }//GEN-LAST:event_MenuAboutMouseExited

    private void MenuLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLogOutMouseExited
        // TODO add your handling code here:
        MenuLogOut.setBackground(new Color(238,202,207));
    }//GEN-LAST:event_MenuLogOutMouseExited

    private void MenuUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuUserMouseEntered
        // TODO add your handling code here:
        MenuUser.setBackground(new Color(68, 189, 50));
    }//GEN-LAST:event_MenuUserMouseEntered

    private void MenuUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuUserMouseExited
        // TODO add your handling code here:
        MenuUser.setBackground(new Color(238,202,207));
    }//GEN-LAST:event_MenuUserMouseExited

    private void MenuUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuUserMousePressed
        Content.removeAll();
        Content.add(new User(getUserID()));
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_MenuUserMousePressed

    private void MenuDashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuDashboardMousePressed
        // TODO add your handling code here:
        Content.removeAll();
        Content.add(new DashboardTA());
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_MenuDashboardMousePressed

    private void MenuKueMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuKueMousePressed
        // TODO add your handling code here:
        Content.removeAll();
        Content.add(new MenuKue());
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_MenuKueMousePressed

    private void HistoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoryMousePressed
Content.removeAll();
        Content.add(new history());
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_HistoryMousePressed

    private void MenuPenjualanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuPenjualanMousePressed
        // TODO add your handling code here:
        Content.removeAll();
        Content.add(new Penjualan());
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_MenuPenjualanMousePressed

    private void MenuAboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuAboutMousePressed
        // TODO add your handling code here:
        Content.removeAll();
        Content.add(new MenuAbout());
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_MenuAboutMousePressed

    private void MenuLogOutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLogOutMousePressed
        // TODO add your handling code here:
        new close().setVisible(true);
        dispose();
    }//GEN-LAST:event_MenuLogOutMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
    UIManager.setLookAndFeel( new FlatLightLaf() );
} catch( Exception ex ) {
    System.err.println( "Failed to initialize LaF" );
}
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String userID = "ID";
                new Mainframe(userID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pallete.Gradient BarAtas;
    private javax.swing.JPanel Content;
    private javax.swing.JPanel History;
    private javax.swing.JPanel MenuAbout;
    private javax.swing.JPanel MenuDashboard;
    private javax.swing.JPanel MenuKue;
    private javax.swing.JPanel MenuLogOut;
    private javax.swing.JPanel MenuPenjualan;
    private javax.swing.JPanel MenuUser;
    private javax.swing.JPanel SideBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
