/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tugasakhir1;

/**
 *
 * @author user
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFrame;



public class Penjualan extends javax.swing.JPanel {
    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setTitle("Penjualan");
        frame.setSize(800, 600);
        frame.add(new Penjualan());
        frame.setVisible(true);
    }
    
    

    /**
     * Creates new form Penjualan
     */
    private DefaultTableModel model;
    private String Tanggal;
    
    public Penjualan() {
        initComponents();
        utama();
        Date date = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        tTanggal.setText(s.format(date));
        tTotalBayar.setText("0");
        tBayar.setText("0");
        tKembali.setText("0");
        tTampil.setText("Rp 0,00");
        tampiltransaksi();
    }
    
    
    
    public void totalBiaya(){
        int jumlahBaris = TbPenjualan.getRowCount();
        int totalBiaya = 0;
        int jumlahBarang, hargaBarang;
        for (int i = 0; i < jumlahBaris; i++) {
            jumlahBarang = Integer.parseInt(TbPenjualan.getValueAt(i, 3).toString());
            hargaBarang = Integer.parseInt(TbPenjualan.getValueAt(i, 4).toString());
            totalBiaya = totalBiaya + (jumlahBarang * hargaBarang);
        }
        tTotalBayar.setText(String.valueOf(totalBiaya));
        tTampil.setText("Rp "+ totalBiaya +",00");
    }
    
    private void autonumber(){
        try {
            Connection c = KoneksiRoti.ConfigDB();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM transaksi ORDER BY Nofaktur DESC";
            ResultSet r = s.executeQuery(sql);
            if (r.next()) {
                String NoFaktur = r.getString("NoFaktur").substring(2);
                String RT = "" +(Integer.parseInt(NoFaktur)+1);
                String Nol = "";
                
                if(RT.length()==1)
                {Nol = "000";}
                else if(RT.length()==2)
                {Nol = "00";}
                else if(RT.length()==3)
                {Nol = "0";}
                else if(RT.length()==4)
                {Nol = "";}
                tNoTrans.setText("RT" + Nol + RT);
            } else {
                tNoTrans.setText("RT0001");
            }
            r.close();
            s.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    public void kosong(){
        DefaultTableModel model = (DefaultTableModel) TbPenjualan.getModel();
        
        while (model.getRowCount()>0) {
            model.removeRow(0);
        }
    }
    
    public void utama(){
        tNoTrans.setText("");
        autonumber();
    }
    
    public void clear(){
        tIDCust.setText("");
        tNamaCust.setText("");
        tTotalBayar.setText("0");
        tBayar.setText("0");
        tKembali.setText("0");
        tTampil.setText("0");
    }
    

    public void tambahTransaksi(){

    }  
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tNamaCust = new javax.swing.JTextField();
        tIDCust = new javax.swing.JTextField();
        tNoTrans = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbPenjualan = new javax.swing.JTable();
        bTambah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        tTampil = new javax.swing.JLabel();
        bSimpan = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tTotalBayar = new javax.swing.JTextField();
        tBayar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tKembali = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tTanggal = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1240, 685));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(238, 202, 207));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(246, 172, 182));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kasir Roti");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(534, 534, 534)
                .addComponent(jLabel1)
                .addContainerGap(543, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 70));

        jLabel2.setText("ID Customer");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 173, -1, -1));

        jLabel3.setText("No.Transaksi");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 133, -1, -1));

        jLabel4.setText("Nama Customer");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 213, -1, -1));

        tNamaCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaCustActionPerformed(evt);
            }
        });
        jPanel1.add(tNamaCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 210, 150, -1));
        jPanel1.add(tIDCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 170, 150, -1));

        tNoTrans.setEnabled(false);
        jPanel1.add(tNoTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 130, 150, -1));

        TbPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TbPenjualan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 346, 991, 182));

        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });
        jPanel1.add(bTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(1054, 369, -1, 36));

        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        jPanel1.add(bHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1054, 423, -1, 35));

        tTampil.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tTampil.setText("Rp. 0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(tTampil, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tTampil, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, -1, -1));

        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(bSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, -1, 52));

        jLabel10.setText("Total Bayar");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 540, -1, -1));

        tTotalBayar.setEnabled(false);
        tTotalBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTotalBayarActionPerformed(evt);
            }
        });
        jPanel1.add(tTotalBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 540, 134, -1));

        tBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBayarActionPerformed(evt);
            }
        });
        jPanel1.add(tBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 580, 134, -1));

        jLabel11.setText("Bayar");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 580, -1, -1));

        tKembali.setEnabled(false);
        tKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(tKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 620, 134, -1));

        jLabel12.setText("Kembali");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 620, -1, -1));

        jLabel13.setText("Tanggal");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(894, 101, -1, -1));

        tTanggal.setEnabled(false);
        jPanel1.add(tTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(949, 98, 178, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/—Pngtree—a delicious dish of donuts_4412033.png"))); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 150, -1, 240));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/—Pngtree—pink  double layer birthday_5378649.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 440, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/selai-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 70, 170, 330));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/selai-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 70, 360, 330));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/selai-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 360, 360));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/selai-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 360, 330));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/mini.png"))); // NOI18N
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 510, 160, 170));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tKembaliActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_tKembaliActionPerformed

    private void tBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBayarActionPerformed
        // TODO add your handling code here
        int total, bayar, kembalian;

        total = Integer.valueOf(tTotalBayar.getText());
        bayar = Integer.valueOf(tBayar.getText());

        if (total > bayar) {
            JOptionPane.showMessageDialog(null, "Uang tidak cukup untuk melakukan pembayaran");
        } else {
            kembalian = bayar - total;
            tKembali.setText(String.valueOf(kembalian));
        }
    }//GEN-LAST:event_tBayarActionPerformed

    private void tTotalBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTotalBayarActionPerformed

    }//GEN-LAST:event_tTotalBayarActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) TbPenjualan.getModel();

        String noTransaksi = tNoTrans.getText();
        String tanggal = tTanggal.getText();
        String idCustomer = tIDCust.getText();
        String total = tTotalBayar.getText();

        try {
            Connection c = KoneksiRoti.ConfigDB();
            String sql = "INSERT INTO transaksi(Nofaktur, id_customer, tanggal, TotalBeli) VALUES (?, ?, ?, ?)";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, noTransaksi);
            p.setString(2, idCustomer);
            p.setString(3, tanggal);
            p.setString(4, total);
            p.executeUpdate();
            p.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        try {
            Connection c = KoneksiRoti.ConfigDB();
            int baris = TbPenjualan.getRowCount();

            for (int i = 0; i < baris; i++) {
                TbPenjualan.getValueAt(i, 0);
            }
            String sql = "INSERT INTO penjualan_detail(NoFaktur, ID_Barang, Nama_Barang, Jumlah, Harga, Total) VALUES(?,?,?,?,?,?)";
            PreparedStatement p = c.prepareStatement(sql);
            p.executeUpdate();
            p.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
        clear();
        utama();
        autonumber();
        kosong();
        tTampil.setText("Rp. 0");
        
        deleteform();
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        deleteform();
        clear();
        tampiltransaksi();
        tBayar.setText("0");
        tKembali.setText("0");
    }//GEN-LAST:event_bHapusActionPerformed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        boolean closeable = true;
        listbrg data = new listbrg(null, closeable);
        data.setVisible(true);
        tampiltransaksi();


    }//GEN-LAST:event_bTambahActionPerformed

    private void tNamaCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaCustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaCustActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TbPenjualan;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton bTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tBayar;
    private javax.swing.JTextField tIDCust;
    private javax.swing.JTextField tKembali;
    private javax.swing.JTextField tNamaCust;
    private javax.swing.JTextField tNoTrans;
    private javax.swing.JLabel tTampil;
    private javax.swing.JTextField tTanggal;
    private javax.swing.JTextField tTotalBayar;
    // End of variables declaration//GEN-END:variables
void tampiltransaksi(){
        model = new DefaultTableModel();
        TbPenjualan.setModel(model);
        model.addColumn("ID Barang");
        model.addColumn("Nama Barang");
        model.addColumn("Harga");
        model.addColumn("Jumlah");
        model.addColumn("Total");
        
        try {
            String sql = "SELECT * FROM transsementara";
            java.sql.Connection conn = KoneksiRoti.ConfigDB();
            java.sql.Statement statement = conn.createStatement();
            java.sql.ResultSet resultSet = statement.executeQuery(sql);
            while(resultSet.next()){
            model.addRow(new Object[]{resultSet.getString("id_barang"),resultSet.getString("Nama_barang"),resultSet.getString("Harga"),resultSet.getString("jumlah"),resultSet.getString("subtotal")});
            }
            TbPenjualan.setModel(model);
            totalBiaya();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


void deleteform(){
            try {
            String sql = "DELETE FROM transsementara";
            java.sql.Connection conn = KoneksiRoti.ConfigDB();
            java.sql.Statement statement = conn.createStatement();
            statement.execute(sql);
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
}

}
